name: starterwrkflow

on:
  push:
    branches:
    - main
    


jobs:
  build-job:
    name: display info
    runs-on: ubuntu-latest
    steps:
    - name: task1
      run: uname -a
    - name: task2
      run: hostname
    - name: task3
      run: sleep 5
    - name: build job status
      run: echo "build job completed"

  test-job:
    name: display info
    runs-on: ubuntu-latest
    steps:
    - name: task1
      run: uname -a
    - name: task2
      run: hostname
    - name: task3
      run: sleep 5
    - name: test job status
      run: echo "test job completed"

