name: starterwrkflow

on:
  push:
    branches:
    - main
    

jobs:
  build-job:
    name: on self hosted
    runs-on: raman-test
    steps:
    - name: task1
      run: uname -a
    - name: task2
      run: hostname
    - name: task3
      run: sleep 5
    - name: task4
      run: |
        touch /tmp/ramankhannatest
        echo "hi from remote" > /tmp/ramankhannatest
        echo " value of repouser is ${{ vars.user1 }} and server name is ${{ vars.servername }}
        echo " $user1 "
        
      
    - name: build job status
      run: echo "build job completed"

  test-job:
    name: on github hosted
    runs-on: ubuntu-latest
    steps:
    - name: task1
      run: uname -a
    - name: task2
      run: hostname
    - name: task3
      run: sleep 5
    - name: test job status
      run: echo "test job completed"

