name: starterwrkflow

on:
  workflow_dispatch:
    

jobs:
  build-job:
    name: on self hosted
    runs-on: raman-test
    steps:
    - name: task1
      run: uname -a
    - name: task2
      run: hostname
    - name: task3
      run: sleep 5
    - name: task4
      run: touch /ramankhanna/testfile
    - name: build job status
      run: echo "build job completed"

  test-job:
    name: on github hosted
    runs-on: ubuntu-latest
    steps:
    - name: task1
      run: uname -a
    - name: task2
      run: hostname
    - name: task3
      run: sleep 5
    - name: test job status
      run: echo "test job completed"

