name: workflow2
on:
  push:
    branches:
    - main
  workflow_dispatch:
  
env:
  user1: ramanenvv
  

jobs:
  build:
    env: 
      user2: gaganjob
    name: 1st stage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: step2
      env:
        user3: sandeepstep
      run: |
        ls -ltr
        echo " repo name is ${{ GITHUB.REPOSITORY }} and runner name is ${{ RUNNER.NAME }} "
        echo " value of user1,2,3 are  $user1 , $user2 , $user3 "
        echo " value of repouser is ${{ vars.user1 }} and server name is ${{ vars.servername }} "
        pwd
        java -version
        
  test:
    env: 
      user2: gaganjob2
    name: 2nd stage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: step2
      env:
        user3: sandeepstep2
      run: |
        ls -ltr
        echo " repo name is ${{ GITHUB.REPOSITORY }} and runner name is ${{ RUNNER.NAME }} "
        echo " value of user1,2,3 are $user1 , $user2 , $user3 "
        pwd
        java -version   
        
    - name: print stage
      run: echo " value of user1,2,3 are  $user1 , $user2 , $user3 "
        
    
