name: workflow2
on: 
  # push:
  #   branches:
  #   - main
  workflow_dispatch:
env:
  user1: ramanenv
  

jobs:
  build:
    env: 
      user2: gaganjob
    name: 1st stage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: step2
      env:
        user3: sandeepstep
      run: |
        ls -ltr
        echo " repo name is ${{ GITHUB.REPOSITORY }} and runner name is ${{ RUNNER.NAME }} "
        echo " value of user1,2,3 are : $user1 , $user2 , $user3 "
        pwd
        java -version 
        
  test:
    name: 2nd stage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: step2
      run: |
        ls -ltr
        echo " repo name is ${{ GITHUB.REPOSITORY }} and runner name is ${{ RUNNER.NAME }} "
        echo " value of user1,2,3 are : $user1 , $user2 , $user3 "
        pwd
        java -version   
    - name: test stage
      run: echo " value of user1,2,3 are : $user1 , $user2 , $user3 "
        
    
