name: Download Artifact Workflow

on: [workflow_dispatch]
#  workflow_run:
#    workflows: ["Upload Artifact Workflow"]
#    types:
#      - completed

jobs:
  download-artifact:
    name: Download Artifact and Display
    runs-on: ubuntu-latest

    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: output-artifact

      - name: Display content of the downloaded file
        run: cat output.txt
