name: Download Artifact Workflow

on: [workflow_dispatch]
#  workflow_run:
#    workflows: ["Upload Artifact Workflow"]
#    types:
#      - completed

jobs:
  download-artifact:
    name: Download Artifact and Display
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: output-artifact
          path: outputfolder/output.txt

      - name: Display structure of downloaded files
        run: ls -R
